name: design_system
description: "Design system package for my apps"
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.36.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0

flutter:
  assets:
  - assets/font/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/font/DMSans-Thin.ttf
          weight: 100
        - asset: assets/font/DMSans-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/font/DMSans-ExtraLight.ttf
          weight: 200
        - asset: assets/font/DMSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/font/DMSans-Light.ttf
          weight: 300
        - asset: assets/font/DMSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/font/DMSans-Regular.ttf
          weight: 400
        - asset: assets/font/DMSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/font/DMSans-Medium.ttf
          weight: 500
        - asset: assets/font/DMSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/font/DMSans-SemiBold.ttf
          weight: 600
        - asset: assets/font/DMSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/font/DMSans-Bold.ttf
          weight: 700
        - asset: assets/font/DMSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/font/DMSans-ExtraBold.ttf
          weight: 800
        - asset: assets/font/DMSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/font/DMSans-Black.ttf
          weight: 900
        - asset: assets/font/DMSans-BlackItalic.ttf
          weight: 900
          style: italic


