name: core_l10n
description: "Core l10n package for my apps"
version: 0.0.1
homepage: null
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.16.9"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0

flutter:
  generate: true
